import type { Metadata } from "next";
import "./globals.css";
import { Lexend } from "next/font/google";
import FlareCursor from "./flare";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased sm:p-3 text-white main`}
      >
        <FlareCursor />
        {children}
      </body>
    </html>
  );
}
